Changes to support ROS 2
ros/xacro pull request #154
Opened 2017-07-20 18:10 UTC by bponsler

Initial port to get xacro working in ROS 2. Added function to generate a URDF file from a xacro file for use in ROS 2 launch files.

2017-09-13 08:33 UTC, rhaschke requested changes
What's the (general) plan to deal with ROS1 / ROS2 compatibility issues? This PR will break xacro on ROS1.

2017-09-13 08:33 UTC, rhaschke commented on xacro/__init__.py
> +def to_urdf(xacro_path, urdf_path=None):
Why should we have this additional function? Shouldn't `ros_launch` call xacro as usual?

2018-01-04 05:15 UTC, bponsler commented
Sorry for the delay in replying to your comments.

@rhaschke this PR was intended just to make these changes to support xacro in ros2 known to others and work to merge these changes into a single repo. The function was added because roslaunch works differently under ros2 (it is python) and I figured calling the python function directly would be better than using a system call to execute xacro but I’m not tied to a solution.

@codebot indeed that would be awesome. Not entirely sure how to handle the package.xml changes to go between ros1 and 2. Maybe it would be better as a pure python package instead of a ros package?

2018-02-22 21:54 UTC, traversaro commented
> Maybe it would be better as a pure python package instead of a ros package? 

:+1: 

Transforming `xacro` in a pure python package would be also really convenient to install it on non-ROS friendly environment such as Windows or "strange" Linux distributions.

2018-03-27 21:20 UTC, rhaschke commented
I made ROS imports optional in #159. However, to make the package a pure python package, some more work needs to be done...

2019-09-17 17:52 UTC, gonzodepedro commented
Working on port on #211

2019-09-17 17:52 UTC, closed without merging