Small fixes to make it work with Python 3
ros/xacro pull request #158
Opened 2017-08-29 06:08 UTC by kartikmohta

Note that two tests fail due to internal changes in Python 3:
- test_iterable_literals_eval: The order of keys in dict changed in Py3
- test_no_evaluation: ast.literal_eval('5 -2') gives 3 in Py3

2017-09-12 21:39 UTC, rhaschke commented
I'm wondering whether these changes are really neccessary. Did you have specific issues running xacro with python3? Running the unittests on my side, I don't see any issues.

2017-09-12 22:23 UTC, kartikmohta commented
`cStringIO` and `dict.iteritems` are not present in Python 3, so these changes are required.

2017-09-12 23:03 UTC, rhaschke requested changes
Additionally to your requested changes, I had to
import xml.dom.minidom
in xmlutils.py. Strange, that you didn't notice that issue.

2017-09-12 23:03 UTC, rhaschke commented on src/xacro/__init__.py
> +        for k, v in symbols.redefined.items():
Although iteritems() is more efficient than items() in python2, I think for the sake of simplicity, we can switch to items().

2017-09-12 23:03 UTC, rhaschke commented on xacro.py
> +sys.path = [a for a in sys.path if a not in [this_dir, this_dir_cwd]]
This is definitely more pythonic ;-)

2017-09-13 08:10 UTC, rhaschke commented on src/xacro/xmlutils.py
>  import xml
The "import xml" can be removed then.

2017-09-14 15:55 UTC, rhaschke commented
As soon as #161 is merged, I will add some more commits, cleanup and re-issue as a new PR.
I fixed everything for python3 already, such that the unittests pass:
https://travis-ci.org/ubi-agni/xacro

2017-09-15 17:48 UTC, closed without merging